# -*- coding: utf-8 -*-
"""Binance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1maTZP9qD-VsqqLKhZIla76mvDLDqEpi1
"""

pip install python-binance -q

from binance import Client
import pandas as pd
import seaborn as sns

api_key = 'sua api key aqui'
api_secret = 'sua api secret aqui'

client = Client(api_key, api_secret)

# Tudo que pode ser feito com sua conta entre binance e python
account_informations = client.get_account()
for i in account_informations:
    print(i)

assets = account_informations['balances']

for asset in assets:
    if float(asset["free"]) > 0:
        print(asset)

asset = pd.DataFrame(assets)

asset.to_csv('Downloads')

dados = pd.read_csv('Downloads')

df = pd.DataFrame(data=dados)

del df['Unnamed: 0']

dados = df.query('free > 0' or 'locked > 0').head()

dados = dados.rename_axis('número')

dados

ax = sns.distplot(dados['free'])
ax.figure.set_size_inches(14, 6)
ax.set_title('Distribuição de Frequências - Free', fontsize=18)
ax.set_xlabel('Valores', fontsize=14)
ax

