# -*- coding: utf-8 -*-
"""ler_pdf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OeE-aAw89b3QZN_7zYWLrVpJ1KHMazPc
"""

pip install PyPDF2 -q

pip install wordcloud -q

import PyPDF2
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
from PyPDF2 import PdfFileReader

pdf_path='seu pdf aqui'
pdf = PdfFileReader(str(pdf_path))

sumario = pdf.getPage(2)
sumario1 = sumario.extractText()
sumario1

for page in pdf.pages:
    print(page.extractText(),end='\n')

with open('new.txt',mode="w") as output_file:
    for page in pdf.pages:
        text = page.extractText()
        output_file.write(text)

dados = pd.read_csv("new.txt")
df = pd.DataFrame(data=dados)
df

# concatenar as palavras
#all_summary = " ".join(s for s in dados)

# lista de stopword
stopwords = set(STOPWORDS)
stopwords.update(["suas palavras de exceção aqui"])

# gerar uma wordcloud
wordcloud = WordCloud(stopwords=stopwords,
                      background_color="white",
                      width=1600, height=800).generate(all_summary)

novocsv = wordcloud.DataFrame.to_csv('nome_do_arquivo.csv')

# mostrar a imagem final
fig, ax = plt.subplots(figsize=(10,6))
ax.imshow(wordcloud, interpolation='bilinear')
ax.set_axis_off()

plt.imshow(wordcloud);
wordcloud.to_file("airbnb_summary_wordcloud.png")
#wordcloud.to_file("airbnb_summary_wordcloud.png")

proxima parte (remover palavras indesejadas no dataframe, para que eu possa salvar o arquivo tratado como novo csv)