# -*- coding: utf-8 -*-
"""wordcloud.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GYFQbqXJsXHEMzrSFDFZpIYjjCAmHRfI
"""

pip install wordcloud -q

import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

dados = pd.read_excel("seu arquivo de excel aqui", index_col=0)

dados.groupby(by='Sistema').size()

dados.describe()

dados.head()

dados = dados.reset_index()

dados

sistemas = dados['Sistema']

funcionalidade = dados['Funcionalidade']
funcionalidade

# concatenar as palavras
all_summary = " ".join(s for s in funcionalidade)

# lista de stopword
stopwords = set(STOPWORDS)
stopwords.update(["da", "meu", "em", "você", "de", "ao", "os", "ou", "não",
                  "quando", "nada", "tem", "na", "uma"])

# gerar uma wordcloud
wordcloud = WordCloud(stopwords=stopwords,
                      background_color="white",
                      width=1600, height=800).generate(all_summary)

# mostrar a imagem final
fig, ax = plt.subplots(figsize=(10,6))
ax.imshow(wordcloud, interpolation='bilinear')
ax.set_axis_off()

plt.imshow(wordcloud);
wordcloud.to_file("airbnb_summary_wordcloud.png")

